<?php

namespace AppBundle\Repository;

/**
 * FuncionarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuncionarioRepository extends \Doctrine\ORM\EntityRepository
{
}
